name: flutter_remoter
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  clock: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  fake_async: ^1.3.1
  flutter_lints: ^2.0.0
