name: flutter_remoter
description: Remoter aims to simplify handling asynchronous operations and revalidating them.
version: 0.2.0
homepage: https://github.com/sofiyevsr/flutter_remoter
repository: https://github.com/sofiyevsr/flutter_remoter

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  clock: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  fake_async: ^1.3.1
  flutter_lints: ^2.0.0
